/home/dell/anaconda3/envs/sfmaskrcnn/lib/python3.7/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Namespace(batch_size=128, dataroot='../data', dataset='cifar10', imageSize=32, no_cuda=False, num_classes=10, out_dataset='/home/dell/OOD_Detection/deep_Mahalanobis_detector/data/LSUN_resize', outf='../test/25939/', pre_trained_net='/home/dell/OOD_Detection/confidence_estimation/checkpointscifar10_vgg13_baseline_epoch_200.pt', seed=1)
Random Seed:  1
Load model
Traceback (most recent call last):
  File "../src/test_detection.py", line 50, in <module>
    model.load_state_dict(torch.load(args.pre_trained_net))
  File "/home/dell/anaconda3/envs/sfmaskrcnn/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dell/anaconda3/envs/sfmaskrcnn/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dell/anaconda3/envs/sfmaskrcnn/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/OOD_Detection/confidence_estimation/checkpointscifar10_vgg13_baseline_epoch_200.pt'
